pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }
    
    stages {
        stage ('Deploy Fruit-Veg Web app') {
           steps {
           sshagent (credentials: ['AWS-SSH-KEY']) {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@172.31.37.187 'cd ~ ;
                sudo apt install nginx -y ;
                sudo systemctl daemon-reload ;
                sudo systemctl enable nginx ;
                sudo systemctl start nginx ;
                sudo rm -rf fruits-veg_market ;
                git clone https://github.com/techbleat/fruits-veg_market.git ;
                cd ~/fruits-veg_market/web ;
                sudo cp ~/fruits-veg_market/web/index.html /var/www/html/index.html'
                """
                 }
             }
          }
        }
     post {
        success {
            echo 'Fruit-Veg Web App deployed successfully'
        }

         failure {
            echo 'Fruit-Veg Web App deployment failed'
        }
    }
}
      
