pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
        AWS_DEFAULT_REGION = 'us-east-2'
    }
    
    stages {
        stage ('checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/ayodelebwj/week-7-project.git'
            }
        }

        stage ('build web ami') {
           steps {
            sh 'ls -ltr'
            dir ('packer-ami') {
                sh 'pwd'
                sh 'ls -ltr'
                sh 'packer init .'
                sh 'packer fmt .'
                sh 'packer validate .'
                sh 'packer build web-ami.pkr.hcl'
             }
          }
        }
         stage ('build app ami') {
           steps {
            dir ('packer-ami') {
                sh 'pwd'
                sh 'ls -ltr'
                sh 'packer fmt .'
                sh 'packer validate .'
                sh 'packer build app-ami.pkr.hcl'
             }
          }
        }
    }
     post {
        success {
            echo 'AMI built successfully'
        }

         failure {
            echo 'AMI build failed'
        }
    }
}