pipeline {
    agent any

    environment {
    AWS_ACCESS_KEY_ID = credentials ('aws-access-key-id')
    AWS_SECRET_ACCESS_KEY = credentials ('aws-secret-access-key')
    AWS_DEFAULT_REGION = 'us-east-2'
    }

    stages {
        stage ('terraform init') {
            steps {
                dir ('terraform-infrastructure') {
                    sh 'terraform init'
                    sh 'terraform fmt .'
                    sh 'terraform validate .'
                }
            }
        }

        stage ('terraform plan') {
            steps {
                dir ('terraform-infrastructure') {
                    sh 'terraform plan'
                }
            }
        }

        stage ('terraform apply') {
            steps {
                dir ('terraform-infrastructure') {
                    sh 'terraform apply --auto-approve'
                }
            }
        }
    }

    post {
        success {
            echo 'Infrastructure provisioned successfully'
        }

         failure {
            echo 'Infrastructure provision failed'
        }
    }
}
